### ISSUE TITLE
change into O(1)

### ISSUE THREAD

**Issue by seahmin** [SecondRicecake/sum_test#1]
https://github.com/SecondRicecake/sum_test/commit/d36349da8c13fbc09d07fabc8881d8150be89d7e

**Comment by SecondRicecake** [comment]
done in https://github.com/SecondRicecake/sum_test/commit/a3841a84f064183e30f16234be01005ea0a2e103

**Comment by seahmin** [comment]
don't close!

**Comment by seahmin** [comment]
Look at me!

**Comment by ruinalen** [comment]
LOL :) 👍
